[package]
name = "es-client"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Blocking client for the es binary protocol"

[features]
default = ["tls"]
tls = ["dep:rustls", "dep:rustls-pki-types"]

[dependencies]
es-protocol = { workspace = true }
flate2 = { workspace = true }
rustls = { workspace = true, optional = true }
rustls-pki-types = { workspace = true, optional = true }

[dev-dependencies]
es-broker = { path = "../es-broker" }
reqwest = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
